### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by lypla** [tsinghua-fib-lab/CLSR#10]
Hello, has the Kuaishou dataset been released? How to obtain the dataset?

**Comment by p501501** [comment]
> 您好，快手数据集发布了吗？如何获取数据集？

你好，你训练出淘宝数据集了吗

**Comment by DavyMorgan** [comment]
We have released the pretrained model, as well as the link to the data files of the Taobao dataset.
Please check [model](https://github.com/tsinghua-fib-lab/CLSR#pretrained-model-evaluation) and [data](https://github.com/tsinghua-fib-lab/CLSR#data-pre-processing).

**Comment by DavyMorgan** [comment]
We have released the pretrained model, as well as the link to the data files of the Taobao dataset.
