### ISSUE TITLE
对比试验疑问

### ISSUE THREAD

**Issue by lypla** [tsinghua-fib-lab/CLSR#11]
你好，我对您的实验十分感兴趣，请问您代码里的其他模型能不能直接拿来做对比实验，我试了一下您代码里集成的其他模型，但是失败了，请问需要做哪些调整？十分感谢！

**Comment by DavyMorgan** [comment]
能发一下具体的错误信息吗？谢谢。

**Comment by lypla** [comment]
我想通过你集成好的代码来进行对比试验，直接修改sequential.py里的model参数可以吗？我这么操作后结果仍显示是CLSR模型的实验结果。

**Comment by DavyMorgan** [comment]
通过指定model参数就可以，比如`python sequential.py --dataset taobao --model SLIREC`
