### ISSUE TITLE
Bug in model SLIREC

### ISSUE THREAD

**Issue by xuhao-anhe** [tsinghua-fib-lab/CLSR#12]
Thank u for your contribution
When I use SLIREC to do comparative experiments, It has the following error:
command i used: python sequential.py --dataset taobao --model SLIREC

  File "sequential.py", line 350, in main
    model = get_model(flags_obj, model_path, summary_path, user_vocab, item_vocab, cate_vocab, train_num_ngs)
  File "sequential.py", line 116, in get_model
    counterfactual_recent_k=flags_obj.counterfactual_recent_k,
  File "/home/wb415/miniconda3/envs/ly3.6/lib/python3.6/site-packages/absl/flags/_flagvalues.py", line 481, in __getattr__
    raise AttributeError(name)
AttributeError: counterfactual_recent_k

What's the reason? Thank you for your attention!

**Comment by DavyMorgan** [comment]
Thanks for pointing this out! We have fixed it by removing the unused argument. Please check the latest codes.

**Comment by xuhao-anhe** [comment]
Thank you very much for your help. I also want to consult the kuaishou dataset. Can you provide a download link

**Comment by DavyMorgan** [comment]
Kuaishou dataset is a private industrial dataset. The release of it requires a process of internal review by the company, and it will be made public after the review process. Please use the Taobao dataset for now.

**Comment by xuhao-anhe** [comment]
ok， thank you very much.
