### ISSUE TITLE
comparison experiments

### ISSUE THREAD

**Issue by lypla** [tsinghua-fib-lab/CLSR#13]
Hello, the kuaishou dataset has not been published yet. Apart from Taobao dataset,are there any other datasets available for comparison experiments in this code? Any suggestions?Thanks!

**Comment by DavyMorgan** [comment]
Hello, you can use the provided data preprocess codes to generate training and test data for your custom datasets. The data preprocess codes can be found at [here](https://github.com/tsinghua-fib-lab/CLSR/blob/92c6c7e069374fa2d7217f3a0987f64ce47e7cad/reco_utils/dataset/sequential_reviews.py#L27). Most of the datasets adopted in sequential recommendation can be used, such as Amazon, Yelp, etc. Good Luck!

**Comment by lypla** [comment]
Thank you very much. When processing the yelp dataset, I noticed that in the sequential_review.py, load_data in the yelp_main uses categories.json, as follows:
“
with open(os.path.join(dirs, 'categories.json'), 'r') as f:
category = json.load(f)
”
When I downloaded the yelp dataset, I found no categories.json.Is the yelp dataset not completely downloaded?
(My download address:https://www.yelp.com/dataset/download）

**Comment by DavyMorgan** [comment]
You can find the category file of the Yelp dataset at [here](https://www.yelp.com/developers/documentation/v3/all_category_list/categories.json).
