### ISSUE TITLE
请教一个小问题

### ISSUE THREAD

**Issue by a514131** [tsinghua-fib-lab/CLSR#14]
请问您在调试代码的时候是怎么输出tensor的具体值的，我尝试了往上的各种方法都报错或者只是输出Tensor("mask:0", shape=(?, 50), dtype=int32)，我也尝试了用tf.enable_eager_execution去掉问号问号的维度再进行sess.run输出值，依然报错，想跟您请教一下您项目调试的方法

**Comment by DavyMorgan** [comment]
可以试一试tf.Print或者sess.run查看tensor具体的数值。

**Comment by a514131** [comment]
谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tsinghua-fib-lab/CLSR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月26日(星期一) 上午10:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tsinghua-fib-lab/CLSR] 请教一个小问题 (Issue #14)





 
可以试一试tf.Print或者sess.run查看tensor具体的数值。
