### ISSUE TITLE
data

### ISSUE THREAD

**Issue by lypla** [tsinghua-fib-lab/CLSR#3]
感谢作者的贡献，本人小白入门，想咨询下您的数据集有下载链接吗？可以分享一下吗，感谢。

**Comment by DavyMorgan** [comment]
我们使用的数据集和SIGIR21的SURGE一致，您可以在SURGE的repo里下载数据: https://github.com/tsinghua-fib-lab/SIGIR21-SURGE

**Comment by DavyMorgan** [comment]
我们提供了数据集的链接[data](https://github.com/tsinghua-fib-lab/CLSR/tree/main/tests/resources/deeprec/sequential)。
