### ISSUE TITLE
Tensorflow版本问题

### ISSUE THREAD

**Issue by lypla** [tsinghua-fib-lab/CLSR#4]
感谢作者的贡献，我想咨询一下您用的Tensorflow版本是1.15.2吗，为什么我用这个版本的tf跑代码的时候，一直报TF警告，比如The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.之类的

**Comment by DavyMorgan** [comment]
warning不影响运行的哈，我后续会考虑优化一下
