### ISSUE TITLE
How to get datasets

### ISSUE THREAD

**Issue by a514131** [tsinghua-fib-lab/CLSR#5]

**Comment by a514131** [comment]
I haven't found the link or processing tool to get the dataset yet

**Comment by DavyMorgan** [comment]
The adopted datasets are the same as SIGIR21 SURGE. You can obtain the datasets at [this repo](https://github.com/tsinghua-fib-lab/SIGIR21-SURGE).

**Comment by DavyMorgan** [comment]
We have provided a Google Drive link to the adopted dataset. You can check [data](https://github.com/tsinghua-fib-lab/CLSR/tree/main/tests/resources/deeprec/sequential).
