### ISSUE TITLE
Where is the Kuaishou dataset? It is an empty dir named Kuaishou in the link of SURGE. 

### ISSUE THREAD

**Issue by JadeStrange** [tsinghua-fib-lab/CLSR#6]
Where is the Kuaishou dataset? It is an empty dir named Kuaishou in the link of SURGE.

**Comment by DavyMorgan** [comment]
The release of Kuaishou dataset requires a process of internal review by the company, and it will be made public after the review process. Please use the Taobao dataset for now.

**Comment by JadeStrange** [comment]
Thank you.
