### ISSUE TITLE
如何体现公式（2）中的V^(t - 1)，Y^(t - 1)？

### ISSUE THREAD

**Issue by Kasonreal** [tsinghua-fib-lab/CLSR#7]
Nice work. 请问在3.2.3 Short-term Interests Encoder中如何体现出公式（2）的f_2的输入？3.2.3和3.2.2的输入都是x_1^u.... x_t^u，但是在公式（1）（2）中输入表示是不一致的。

**Comment by DavyMorgan** [comment]
谢谢你关注我们的工作！公式（2）是通过生成query vector时长短期兴趣不同的逻辑体现的，其中长期兴趣的query vector是直接通过embedding lookup得到，而短期兴趣的query vector是通过GRU从历史交互序列中得到，即公式（6）-（7）。
