### ISSUE TITLE
About your trained model

### ISSUE THREAD

**Issue by zwx980624** [tsinghua-fib-lab/CLSR#9]
Could you please provide your trained model?
Thank you so much.

**Comment by p501501** [comment]
你好，你训练出淘宝数据集了吗？非常感谢

**Comment by p501501** [comment]
> 你能提供你训练有素的模型吗？ 太感谢了。
1

**Comment by DavyMorgan** [comment]
Thanks for your attention on our work. We have released the pretrained model. Please check [pretrained-model-evaluation](https://github.com/tsinghua-fib-lab/CLSR#pretrained-model-evaluation).
